# ------------------------------------------------------------------------------
# Github Workflow to promote to production environment
#
#   - This pipeline is triggered by a github Pull Request/merge 
#
#   1) Checks out production branch 
#   2) Run an import of all production assets for this project into wM.io PROD environment
#   3) Run predefined tests for this project in wM.io PROD environment
#
# ------------------------------------------------------------------------------
name: Deploy Production
run-name: Promote to Production Environment
on:
  push:
    branches:
      - production
    paths:
      - 'assets/do_not_promote/**'

jobs:
  # -------------------------------
  # Import prod assets to wM.io
  # -------------------------------
  Promote-Prod-Assets:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------
      # Check out production
      # --------------------------------------
      - uses: actions/checkout@v4
        with:
          ref: 'production'
      # --------------------------------------
      # Build Info
      # --------------------------------------
      - name: Build Info
        run: |
          echo Repository: ${{ github.repository }}
          echo Project Name: ${{ vars.WMIO_PROJECT_NAME }}
          echo Run ID: ${{ github.run_id }}
          echo Run Number: ${{ github.run_number }} 
          echo Triggered by: ${{ github.triggering_actor }} 
          echo Github path: ${{ github.workspace }} 
          echo webMethods.io URL: https://${{ vars.WMIO_HOSTNAME_PROD }}:443
          echo webMethods.io Username: ${{ vars.WMIO_USERNAME_PROD }}
      # --------------------------------------
      # Import All Assets
      # --------------------------------------
      - name: Import Assets
        env:
          WMIO_PASSWORD: ${{ secrets.WMIO_PASSWORD_PROD }}
        run:  |
          PROJECT_NAME_URL_ENCODED=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "${{ vars.WMIO_PROJECT_NAME }}")
          WMIO_URL=https://${{ vars.WMIO_HOSTNAME_PROD }}:443

          chmod +x ${{ github.workspace }}/scripts/wmio/*.sh
          ${{ github.workspace }}/scripts/wmio/importAllAssets.sh \
            ${WMIO_URL} \
            ${{ vars.WMIO_USERNAME_PROD }} \
            "$WMIO_PASSWORD" \
            ${PROJECT_NAME_URL_ENCODED} \
            ${{ github.workspace }}
  # -------------------------------
  # Validate PROD with test cases
  # -------------------------------
  Validate-Test:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [Promote-Prod-Assets]
    uses: ./.github/workflows/validation-bruno.yml
    secrets:
      B2B_PASSWORD: ${{ secrets.B2B_PASSWORD_PROD }}
      WMIO_PASSWORD: ${{ secrets.WMIO_PASSWORD_PROD }}

