# ------------------------------------------------------------------------------
# Github Workflow to promote to target environment (Test/Prod)
#
#   - This pipeline is triggered by a github Pull Request/merge 
#
#   1) Checks out particular branch 
#   2) Run an import of all test assets for this project into wM.io target environment
#
# ------------------------------------------------------------------------------
name: Promote
run-name: Import to Target Environment
on:
  workflow_call:
    inputs:
      environment: 
        type: string
        required: true
    secrets:
      WMIO_PASSWORD:
        required: true      
          
jobs:
  # -------------------------------
  # Import assets to wM.io
  # -------------------------------
  Import:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # --------------------------------------
      # Check out project assets branch
      # --------------------------------------
      - uses: actions/checkout@v4
      # --------------------------------------
      # Check out DevOps scripts 
      # --------------------------------------
      - uses: actions/checkout@v4
        with:
          repository: 'HMHansson/ICA-DevOps'
          path: "devops"
      # --------------------------------------
      # Build Info
      # --------------------------------------
      - name: Build Info
        run: |
          echo Repository: ${{ github.repository }}
          echo Project Name: ${{ vars.WMIO_PROJECT_NAME }}
          echo Environment: ${{ inputs.environment }}
          echo Run ID: ${{ github.run_id }}
          echo Run Number: ${{ github.run_number }} 
          echo Triggered by: ${{ github.triggering_actor }} 
          echo Github path: ${{ github.workspace }} 
          echo webMethods.io URL: https://${{ vars.WMIO_HOSTNAME }}:443
          echo webMethods.io Username: ${{ vars.WMIO_USERNAME }}
          echo Triggered by : ${{ github.event_name }}
      # --------------------------------------
      # Import All Assets
      # --------------------------------------
      - name: Import Assets
        run:  |

          PROJECT_NAME_URL_ENCODED=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "${{ vars.WMIO_PROJECT_NAME }}")

          chmod +x ${{ github.workspace }}/devops/scripts/*.sh
          echo "Promoting to ${{ inputs.environment }} environment ......."
          
          # ${{ github.workspace }}/devops/scripts/importAllAssets.sh \
          #  https://${{ vars.WMIO_HOSTNAME }}:443 \
          #  ${{ vars.WMIO_USERNAME }} \
          #  "${{ secrets.WMIO_PASSWORD }}" \
          #  ${PROJECT_NAME_URL_ENCODED} \
          #  ${{ github.workspace }}

