# ------------------------------------------------------------------------------
# Github Workflow to promote to target environment 
#
#   - This pipeline is triggered by a github Pull Request/merge 
#
#   1) Checks out particular branch 
#   2) Run an import of all test assets for this project into wM.io target environment
#
# ------------------------------------------------------------------------------
name: Deploy
run-name: Promote to Environment
on:
  workflow_call:
    secrets:
      WMIO_PASSWORD:
        required: true
    inputs:
      WMIO_ENVIRONMENT:
          type: string
          required: true
  
jobs:
  # -------------------------------
  # Import assets to wM.io
  # -------------------------------
  Promote-Assets:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------
      # Check out project assets test branch
      # --------------------------------------
      - uses: actions/checkout@v4
        with:
          ref: '${{ vars.WMIO_ENVIRONMENT }}'
      # --------------------------------------
      # Check out DevOps scripts 
      # --------------------------------------
      - uses: actions/checkout@v4
        with:
          repository: 'HMHansson/ICA-DevOps'
          path: "devops"
      # --------------------------------------
      # Build Info
      # --------------------------------------
      - name: Build Info
        run: |
          echo Repository: ${{ github.repository }}
          echo Project Name: ${{ vars.WMIO_PROJECT_NAME }}
          echo Environment: ${{ env.WMIO_ENVIRONMENT }}
          echo Run ID: ${{ github.run_id }}
          echo Run Number: ${{ github.run_number }} 
          echo Triggered by: ${{ github.triggering_actor }} 
          echo Github path: ${{ github.workspace }} 
          if [[ "${{ env.WMIO_ENVIRONMENT }}" == "development" ]]; then
            echo "WMIO_HOSTNAME=${{ vars.WMIO_HOSTNAME_DEV }}" >> $GITHUB_ENV
            echo "WMIO_USERNAME=${{ vars.WMIO_USERNAME_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ env.WMIO_ENVIRONMENT }}" == "test" ]]; then 
            echo "WMIO_HOSTNAME=${{ vars.WMIO_HOSTNAME_TEST }}" >> $GITHUB_ENV
            echo "WMIO_USERNAME=${{ vars.WMIO_USERNAME_TEST }}" >> $GITHUB_ENV
          elif [[ "${{ env.WMIO_ENVIRONMENT }}" == "production" ]]; then 
            echo "WMIO_HOSTNAME=${{ vars.WMIO_HOSTNAME_PROD }}" >> $GITHUB_ENV
            echo "WMIO_USERNAME=${{ vars.WMIO_USERNAME_PROD }}" >> $GITHUB_ENV
          else
            echo invalid environment name ${{ env.WMIO_ENVIRONMENT }}
            exit 1
          fi
          echo webMethods.io URL: https://${{ env.WMIO_HOSTNAME }}:443
          echo webMethods.io Username: ${{ env.WMIO_USERNAME }}

      # --------------------------------------
      # Import All Assets
      # --------------------------------------
      - name: Import Assets
        run:  |

          PROJECT_NAME_URL_ENCODED=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "${{ vars.WMIO_PROJECT_NAME }}")
          WMIO_URL=https://${{ env.WMIO_HOSTNAME }}:443

          chmod +x ${{ github.workspace }}/devops/scripts/*.sh
          ${{ github.workspace }}/devops/scripts/importAllAssets.sh \
            ${WMIO_URL} \
            ${{ env.WMIO_USERNAME }} \
            "${{ secrets.WMIO_PASSWORD }}" \
            ${PROJECT_NAME_URL_ENCODED} \
            ${{ github.workspace }}

