# ------------------------------------------------------------------------------
# Github Workflow to validate functionality using Postman Collections
#
#  - This pipeline is triggered by
#     a) Manually start this workflow (from Github actions)
#     b) commit/push bron test cases to development branch (using git client)
#     c) development commit/merge (called via workflow_call - commit-development)
#     d) test PR/merge (called via workflow_call - promote-test)
#     e) production PR/merge (called via workflow_call - promote-production)
#
# ------------------------------------------------------------------------------
name: Dev Test Case Validation
run-name: Project Test Cases
on:
  workflow_call:
    secrets:
      B2B_PASSWORD:
        required: true
      WMIO_PASSWORD:
        required: true
    inputs:
      WMIO_PROJECT_NAME: 
        type: string
        required: true
      WMIO_HOSTNAME: 
        type: string
        required: true
      WMIO_USERNAME: 
        type: string
        required: true
      WMIO_ENVIRONMENT: 
        type: string
        required: false

env:
  BRUNO_COLLECTION: "${{ github.workspace }}/test/TestCollection"
  WMIO_ENVIRONMENT: "development"  # Default environment

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------
      # Checkout branch
      # --------------------------------------
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      # --------------------------------------
      # Run Info
      # --------------------------------------
      - name: Run Info
        run: |
          echo Repository: ${{ github.repository }}
          echo Project Name: ${{ vars.WMIO_PROJECT_NAME }}
          echo Environment: ${{ vars.WMIO_ENVIRONMENT }}
          echo Run ID: ${{ github.run_id }}
          echo Run Number: ${{ github.run_number }} 
          echo Triggered by: ${{ github.triggering_actor }} 
          echo Github path: ${{ github.workspace }} 
          echo webMethods.io URL: https://${{ vars.WMIO_HOSTNAME }}:443
          echo webMethods.io Username: ${{ vars.WMIO_USERNAME }}
          echo Triggered by : ${{ github.event_name }}
      # --------------------------------------
      # Conditions
      # --------------------------------------
      - name: Test conditions
        run: |
          echo Triggered by event: ${{ github.event_name }}
          if test -d "${{ env.BRUNO_COLLECTION }}"; then
            echo Test collection found for ${{ vars.WMIO_PROJECT_NAME }} ...
          else
            echo No test cases found for ${{ vars.WMIO_PROJECT_NAME }} ...
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi
          
          # Set environment for Bruno to use (default: development)
          if [ "${{ github.ref }}" == "refs/heads/development" ]; then
            echo Running Bruno Tests for the DEVELOPMENT environment.
            echo "WMIO_ENVIRONMENT=development" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            echo "WMIO_ENVIRONMENT=test" >> $GITHUB_ENV
            echo Running Bruno Tests for the TEST environment.
          elif [ "${{ github.ref }}" == "refs/heads/production" ]; then
            echo "WMIO_ENVIRONMENT=production" >> $GITHUB_ENV
            echo Running Bruno Tests for the PRODUCTION environment.
          fi

      # ------------------------------------------------------
      # Run Bruno Tests 
      # ------------------------------------------------------
      - name: Install Bruno CLI
        run: |
          cd ${{ env.BRUNO_COLLECTION }}
          npm install @usebruno/cli -g
          npm install xml2js
      - name: Run Bruno Tests
        run: |
          cd ${{ env.BRUNO_COLLECTION }}

          # ----------------------------
          #  Run collection
          # ----------------------------
          bru run --env ${{ env.WMIO_ENVIRONMENT }} --env-var B2B_PASSWORD=${{ secrets.B2B_PASSWORD }} --env-var WMIO_PASSWORD=${{ secrets.WMIO_PASSWORD }} --bail -f junit -o ${{ env.BRUNO_COLLECTION }}/bruno-junit.xml
      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '${{ env.BRUNO_COLLECTION }}/bruno-junit.xml'
