# ------------------------------------------------------------------------------
# Github Workflow to validate functionality using Postman Collections
#
#  - This pipeline is triggered by
#     a) Manually start this workflow (from Github actions)
#     b) commit/push bron test cases to development branch (using git client)
#     c) development commit/merge (called via workflow_call - commit-development)
#     d) test PR/merge (called via workflow_call - promote-test)
#     e) production PR/merge (called via workflow_call - promote-production)
#
# ------------------------------------------------------------------------------
name: Dev Test Case Validation
run-name: Project Test Cases
on:
  workflow_call:
    inputs:
      environment: 
        type: string
        required: false

env:
  TEST_DIR: "${{ github.workspace }}/test/TestCollection"

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # --------------------------------------
      # Checkout branch
      # --------------------------------------
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      # --------------------------------------
      # Run Info
      # --------------------------------------
      - name: Run Info
        run: |
          echo Repository: ${{ github.repository }}
          echo Project Name: ${{ vars.WMIO_PROJECT_NAME }}
          echo Environment1: ${{ env.environment }}
          echo Environment2: ${{ vars.environment }}
          echo Environment3: ${{ inputs.environment }}
          echo Run ID: ${{ github.run_id }}
          echo Run Number: ${{ github.run_number }} 
          echo Triggered by: ${{ github.triggering_actor }} 
          echo Github path: ${{ github.workspace }} 
          echo webMethods.io URL: https://${{ vars.WMIO_HOSTNAME }}:443
          echo webMethods.io Username: ${{ vars.WMIO_USERNAME }}
          echo Triggered by : ${{ github.event_name }}
